name: my_first_test
env:
  APPLICATION_NAME: "my Flask"
  PACKAGE_NAME    : "Flask_deploy_${{ github.sha }}"
on: 
  push:
    branches: 
      - master

jobs:
  my_testing: 
    runs-on: ubuntu-latest
    steps:
      - name: print hello message in testing
        run: echo "hello world from testing job" 
      - name: echo env
        run: |
          echo "my application name -- ${{ env.APPLICATION_NAME }}"
          echo "my PACKAGE_NAME -- ${{ env.PACKAGE_NAME }}"
      - name: clone dir my repo
        uses: actions/checkout@v1
      - name: list dir
        run: ls -la

  my_testing2:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
        - name: print hello message in deploy
          run: echo "hello world from deploy job"
        - name: my PACKAGE_NAME
          run: echo "my PACKAGE_NAME -- ${{ env.PACKAGE_NAME }}"
        - name: clone dir my repo2
          uses: actions/checkout@v2
        - name: list dir
          run: ls -la
