name: test
env:
  APPLICATION_NAME: "my Flask"
  PACKAGE_NAME    : "Flask_deploy_${{ github.sha }}"
on: 
  push:
    branches: 
      - master

jobs:
  my_testing: 
    runs-on: ubuntu-latest
    steps:
      - name: print hello message in testing
        run: echo "hello world from testing job" 
      - name: echo env
        run: |
          echo "my application name -- ${{ env.APPLICATION_NAME }}"
          echo "my PACKAGE_NAME -- ${{ env.PACKAGE_NAME }}"
      - name: list
        run: ls -la
      - name: clone dir my repo
        uses: actions/checkout@v1
      - name: list dir
        run: ls -la

  my_testing2:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      var1: "job variable1"
      var2: "job variable_2"
    steps:
        - name: print hello message in deploy
          run: echo "hello world from deploy job"
        - name: my PACKAGE_NAME
          run: echo "my PACKAGE_NAME -- ${{ env.PACKAGE_NAME }}"
        - name: all variable
          run: |
            echo "var1 - $var1" 
            echo "hello my   $var2" 
            echo "lockal var - $lockar_var"
            echo "global  $APPLICATION_NAME"
            echo "global  $PACKAGE_NAME"
          env:
           lockar_var: "my lockal var" 
        - name: list
          run: ls -la
        - name: clone dir my repo2
          uses: actions/checkout@v2
