name: test
env:
  APPLICATION_NAME: "my Flask"
  PACKAGE_NAME    : "Flask_deploy_${{ github.sha }}"
on: 
  push:
    branches: 
      - master

jobs:
  my_testing: 
    runs-on: ubuntu-latest
    steps:
      - name: print hello message in testing
        run: echo "hello world from testing job" 
      - name: echo env
        run: |
          echo "my application name -- ${{ env.APPLICATION_NAME }}"
          echo "my PACKAGE_NAME -- ${{ env.PACKAGE_NAME }}"
      - name: list
        run: ls -la
      - name: clone dir my repo
        uses: actions/checkout@v4
      - name: list dir
        run: ls -la
